### ISSUE TITLE
Fault Detection of 'arduino-library' topic due to bash script error

### ISSUE THREAD

**Issue by nkaaf** [adafruit/ci-arduino#178]
The execution of my workflow was successful, but I saw the warning
"Warning: arduino-library is not found in this repo topic. Please add this tag in the About repo". I double checked my repo topics, but "arduino-library" is in there.

In the line above the warning, there is a bash error "ci/actions_install.sh: line 40: {: command not found".

I try to find the reason for this error and request a pull request after finding out the problem.

Workflow Source: https://github.com/nkaaf/Arduino-List/blob/638a66afd49261b5cf2b9fd690d9808c05a242c2/.github/workflows/githubci.yml
Workflow execution: https://github.com/nkaaf/Arduino-List/actions/runs/7781242146/job/21215312938

**Comment by tyeth** [comment]
It occurred to me we could eventually get a length issue, so maybe echoing the variable to jq in the second line is more sensible (passing as STDIN rather than command line arguments)
```
repo_topics=$(curl -f --request GET --url "https://api.github.com/repos/$GITHUB_REPOSITORY" || echo '{"topics":[]}')
repo_topics=$(echo $repo_topics | jq -r '.topics[]' )
```

**Comment by nkaaf** [comment]
I have tested your second approach too and it worked. The output of a private/non-existing repository would be the error message of curl, that 404 occurred. If you want to, you can close my PR #179 and create a new one with your solution.
