### ISSUE TITLE
doxy_gen_and_deploy.sh assumes it run on Travis

### ISSUE THREAD

**Issue by edgar-bonet** [adafruit/ci-arduino#74]
Although the script attempts to support both Travis and GitHub actions, in some parts it still assumes it runs on Travis. For instance, [line 81][]:

```shell
git config user.email "travis@travis-ci.org"
```

and [line 168][]:

```shell
git commit -m "Deploy code docs to GitHub Pages Travis build: ${TRAVIS_BUILD_NUMBER}" -m "Commit: ${TRAVIS_COMMIT}"
```

This results in commits like [this one][commit]:

```text
commit 57834c85e08e3dd436743a59b72f2d888dafd2c5
Author: Doxygen CI <travis@travis-ci.org>
Date:   Thu Apr 23 17:51:50 2020 +0000

    Deploy code docs to GitHub Pages Travis build:
    
    Commit:
```

[line 81]: ../blob/37dc6a11467f25e26f81db2022e60473b2e69d1f/doxy_gen_and_deploy.sh#L81
[line 168]: ../blob/37dc6a11467f25e26f81db2022e60473b2e69d1f/doxy_gen_and_deploy.sh#L168
[commit]: /adafruit/RTClib/commit/57834c85e08e3dd436743a59b72f2d888dafd2c5

**Comment by ladyada** [comment]
feel free to submit a PR

**Comment by edgar-bonet** [comment]
I just submitted pull request #91 addressing this issue.
