### ISSUE TITLE
gh-pages gets pushed to from branches

### ISSUE THREAD

**Issue by evaherrada** [adafruit/ci-arduino#79]
@ladyada What I've noticed is that gh-pages will get pushed to from branches other than master. I don't think this is really desired, so I can try to add a check to see if the branch is master or main before pushing to gh-pages but I wanted to check with you before starting on it in case it wasn't something you felt like needs fixing or not something you wanted me to fix.

**Comment by ladyada** [comment]
sure you can add special main/master-only handling
