### ISSUE TITLE
Github build will break soon, fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by zjwhitehead** [adafruit/ci-arduino#90]
Currently the actions_install.sh script fails due to unmet llvm requirements in Ubuntu 20.04 
![image](https://user-images.githubusercontent.com/4623792/103238357-7b344d00-4918-11eb-8e67-94263b942d85.png)

The `example_actions.yml` as well as many other libraries [specifies](https://github.com/adafruit/ci-arduino/blob/master/example_actions.yml#L7) `runs-on: ubuntu-latest`

![image](https://user-images.githubusercontent.com/4623792/103238929-2b568580-491a-11eb-9f8a-6aa38dfe93c9.png)

[Github indicates](https://github.com/actions/virtual-environments/issues/1816) the transition to 20.04 for ubuntu-latest is already happening which means more builds will start breaking soon. 

## Potential fix
changing in `actions_install.sh` to use `libllvm8=1:8.0.1-9 -V` seems to work but needs further testing. Also its not backwards compatible with 18.04 so further work will be required to update the script to handle both versions.
![image](https://user-images.githubusercontent.com/4623792/103239043-707ab780-491a-11eb-9f99-8dd5863ef214.png)

**Bonus:** For now pinning the example config to `ubuntu-18.04` is probably worth it...

**Comment by ladyada** [comment]
hmm! can you submit a PR? we'll try it out :)

**Comment by dhalbert** [comment]
Stopgap fix: https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/1474 for now. We should update the whole `clang-format` checker.

**Comment by ladyada** [comment]
this was fixed i guess cause it works now!
